kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
       - name: tomcat
         image: 24121986/ubuntu1:latest
         ports:
          - containerPort: 80





---


kind: Service
apiVersion: v1
metadata:
  name: service1
spec:
  type: LoadBalancer
  selector:
     app: tomcat
  ports:
   - name: http
     protocol: "TCP"
     port: 80
     targetPort: 80
